name: Benchmarks

on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:
    branches:
      - 'main'
      - 'next'
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks Charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install --with-deps
      - run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/CodSpeedHQ/runner/releases/download/v2.4.3/codspeed-runner-installer.sh | sh
      - run: PATH=$PATH:$HOME/.cargo/env
      - run: codspeed-runner --token=${{ secrets.CODSPEED_TOKEN }} -- pnpm test:performance
  benchmarks-action:
    name: Benchmarks Charts Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpx playwright install --with-deps
      - name: Run benchmarks
        uses: CodSpeedHQ/action@a58b84c0b61569a9cbb7cfb378cc849d65cf1ce5
        with:
          run: pnpm test:performance
          token: ${{ secrets.CODSPEED_TOKEN }}
  benchmarks-no-codspeed:
            name: Benchmarks Charts No Codspeed
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
              - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
                with:
                  run_install: false
              - name: Use Node.js 20.x
                uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
                with:
                  node-version: 20
                  cache: 'pnpm'
              - run: pnpm install --frozen-lockfile
              - run: pnpx playwright install --with-deps
              - run: pnpm test:performance